[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool.poetry]
name = "WestJR"
version = "0.4.3"
description = "Handling of train operation information of JR West, a railroad company in Japan"
license = "Unlicense"
authors = [
  "unyacat <admin@unyacat.net>",
]
readme = "README.md"
repository = "https://github.com/unyacat/westjr"
keywords = [
  "westjr",
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: Implementation :: CPython",
]
packages = [
  { include = "westjr" },
]
dependencies.python = ">=3.7,<4"
dependencies.pydantic = "^2.0.3"
dependencies.requests = "^2.31.0"
dependencies.types-requests = "^2.31.0"
dependencies.typing-extensions = "^4.7.1"
group.dev.dependencies.mypy = ">=0.991,<1.5"
group.dev.dependencies.pre-commit = ">=2.20,<4.0"
group.dev.dependencies.pytest = "^7.2.2"

[tool.black]
target-version = [
  "py39",
]
line-length = 120

[tool.ruff]
line-length = 120
allowed-confusables = [
  "，",
  "．",
]
ignore = [
  "A003",   # Class attribute `{name}` is shadowing a Python builtin
  "ANN",    # flake8-annotations
  "D",      # pydocstring
  "ERA001", # Found commented-out code
  "N",      # pep8-naming
]
mccabe.max-complexity = 10
per-file-ignores."example.py" = [
  "T201", # `print` found
]
per-file-ignores."tests/test_*.py" = [
  "INP001", # File tests/test_*.py is part of an implicit namespace package. Add an __init__.py.
  "S101",   # Use of assert detected
]
per-file-ignores."westjr/response_types/*.py" = [
  "N815",  # Variable `camelCase` in class scope should not be mixedCase
  "UP006", # Use `dict` / `list` instead of `dict` / `List` for type annotation
  "UP007", # Use `X | Y` for type annotations
  "UP035", # `typing.Dict` / `typing.List` is deprecated, use `dict` / `list` instead
]
select = [
  "ALL",
]

[tool.mypy]
python_version = "3.9"
strict = true
pretty = true
plugins = [
  "pydantic.mypy",
]
show_error_codes = true

[tool]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
